import { Inter } from 'next/font/google'
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import './globals.css'
import Footer1 from './components/Footer1';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        {children}

        {/* <Footer /> */}
        <Footer1 />
      </body>
    </html>
  );
}
